name: haseeb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  firebase_ai: ^3.2.0
  firebase_core: ^4.1.0
  firebase_vertexai: ^2.2.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^2.3.6
  fluttertoast: ^8.2.12
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  record: ^6.0.0
  share_plus: ^11.1.0
  shared_preferences: ^2.1.0
  google_fonts: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/
