// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhgWrss-Vx3HUn0DuTf8_MtPUlKLw9ch0',
    appId: '1:482257513712:web:e158a038a43da694792635',
    messagingSenderId: '482257513712',
    projectId: 'haseeb-34774',
    authDomain: 'haseeb-34774.firebaseapp.com',
    storageBucket: 'haseeb-34774.firebasestorage.app',
    measurementId: 'G-PZ0N7YVTYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2irfd8UURUk3FtzlXilrpZZV971Gu7Es',
    appId: '1:482257513712:android:a6bbba19c2adba36792635',
    messagingSenderId: '482257513712',
    projectId: 'haseeb-34774',
    storageBucket: 'haseeb-34774.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdYuI2fWs2FlwaJkU0Sp9pd36BWP5zG3A',
    appId: '1:482257513712:ios:c814a47dfdff244d792635',
    messagingSenderId: '482257513712',
    projectId: 'haseeb-34774',
    storageBucket: 'haseeb-34774.firebasestorage.app',
    iosBundleId: 'com.example.haseeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdYuI2fWs2FlwaJkU0Sp9pd36BWP5zG3A',
    appId: '1:482257513712:ios:c814a47dfdff244d792635',
    messagingSenderId: '482257513712',
    projectId: 'haseeb-34774',
    storageBucket: 'haseeb-34774.firebasestorage.app',
    iosBundleId: 'com.example.haseeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhgWrss-Vx3HUn0DuTf8_MtPUlKLw9ch0',
    appId: '1:482257513712:web:3c0841c95b03ba8b792635',
    messagingSenderId: '482257513712',
    projectId: 'haseeb-34774',
    authDomain: 'haseeb-34774.firebaseapp.com',
    storageBucket: 'haseeb-34774.firebasestorage.app',
    measurementId: 'G-5QM6DM97W4',
  );
}
